language: php

php:
  - 5.5

# TODO:this is multiple env. we need one env with multiple values
env:
  - IS_TRAVIS=1 DB=mysql DB_HOST=localhost DB_DATABASE=bmfu_test DB_USERNAME=root DB_PASSWORD=""

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS bmfu_test;" -uroot; fi
  - phpenv config-add php_config.ini
  - composer install --no-interaction --prefer-dist
  - sh -c 'cd migrate && composer install --no-interaction --prefer-dist'
  - sh -c 'cd migrate && php artisan migrate --force'

script:
  - vendor/bin/phpunit